"""Decision Signal schemas — adapted from daily_stock_analysis's DecisionSignal
concept (MIT), kept self-contained (no AI/DB dependencies).

A DecisionSignal is an actionable, scored trade idea generated by the
strategy-templates engine: an action (buy/hold/avoid), a 0-100 score, a
confidence, entry/stop/target levels, a horizon, and human-readable reasons.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class DecisionAction(str, Enum):
    BUY = "buy"
    HOLD = "hold"
    AVOID = "avoid"


class DecisionStatus(str, Enum):
    ACTIVE = "active"
    EXPIRED = "expired"
    CLOSED = "closed"


class DecisionHorizon(str, Enum):
    INTRADAY = "intraday"
    SWING = "swing"
    LONG = "long"


class DecisionSignal(BaseModel):
    id: str
    symbol: str
    name: Optional[str] = None
    strategy: str
    display_name: str
    category: str
    action: DecisionAction
    score: int = Field(..., ge=0, le=100)
    confidence: float = Field(..., ge=0.0, le=1.0)
    entry: Optional[float] = None
    stop_loss: Optional[float] = None
    target: Optional[float] = None
    horizon: DecisionHorizon = DecisionHorizon.SWING
    risk_reward: Optional[float] = None
    reasons: List[str] = Field(default_factory=list)
    status: DecisionStatus = DecisionStatus.ACTIVE
    timestamp: datetime


class DecisionSignalListResponse(BaseModel):
    total: int
    buy_count: int
    hold_count: int
    avoid_count: int
    signals: List[DecisionSignal]
    generated_at: datetime
    data_timestamp: Optional[datetime] = None
    source: str = "synthetic"
    is_stale: bool = False


class DecisionSignalFilter(BaseModel):
    action: Optional[DecisionAction] = None
    strategy: Optional[str] = None
    min_score: Optional[int] = Field(None, ge=0, le=100)
    limit: int = Field(50, ge=1, le=200)
